version: "3.9"

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    ports:
     - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sts,iam
      - DEBUG=0
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AWS_MODE=true
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AZURE_MODE=false
      - AZURE_LOCATION=centralindia
      - AZURE_RESOURCE_GROUP=nimbusopt-rg
      - AZURE_VMSS_NAME=nimbusopt-vmss
      - AZURE_ACI_GROUP=nimbusopt-containers
      - SLO_MAX_CPU=85
      - SLO_MAX_MEMORY=90
      - SLO_MAX_REQUESTS=2.0
      - SLO_MIN_REPLICAS=1
      - SLO_MAX_REPLICAS=8
      - SLO_MAX_SCALE_STEP=2
      - SLO_COOLDOWN_SECONDS=30
    ports:
      - "8000:8000"
    depends_on:
      localstack:
        condition: service_healthy
      prometheus:
        condition: service_started
    volumes:
      - ./database:/app/database
      - ./rl_models:/app/app/rl/models

volumes:
  localstack_data:


  